<a href="https://colab.research.google.com/github/dferns11-git/Using-Generative-Adversarial-Networks-to-detect-anomalies-in-network-traffic/blob/main/dataset_builder.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
import pandas as pd
import glob

In [36]:
data_1 = pd.read_csv('/content/drive/MyDrive/Research Project/UNSW-NB15_1.csv', header=None)
data_1

<ipython-input-36-d0485fab7594>:1: DtypeWarning: Columns (1,3,47) have mixed types. Specify dtype option on import or set low_memory=False.
  data_1 = pd.read_csv('/content/drive/MyDrive/Research Project/UNSW-NB15_1.csv', header=None)

,0,1,2,3,4,5,6,7,8,9,...,39,40,41,42,43,44,45,46,47,48
0,59.166.0.0,1390,149.171.126.6,53,udp,CON,0.001055,132,164,31,...,0,3,7,1,3,1,1,1,NaN,0
1,59.166.0.0,33661,149.171.126.9,1024,udp,CON,0.036133,528,304,31,...,0,2,4,2,3,1,1,2,NaN,0
2,59.166.0.6,1464,149.171.126.7,53,udp,CON,0.001119,146,178,31,...,0,12,8,1,2,2,1,1,NaN,0
3,59.166.0.5,3593,149.171.126.5,53,udp,CON,0.001209,132,164,31,...,0,6,9,1,1,1,1,1,NaN,0
4,59.166.0.3,49664,149.171.126.0,53,udp,CON,0.001169,146,178,31,...,0,7,9,1,1,1,1,1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
699996,59.166.0.8,12520,149.171.126.6,31010,tcp,FIN,0.020383,320,1874,31,...,0,8,20,7,5,1,1,4,NaN,0
699997,59.166.0.0,18895,149.171.126.9,80,tcp,FIN,1.402957,19410,1087890,31,...,0,1,1,2,7,2,2,2,NaN,0
699998,59.166.0.0,30103,149.171.126.5,5190,tcp,FIN,0.007108,2158,2464,31,...,0,13,13,6,7,2,1,2,NaN,0
699999,59.166.0.6,30388,149.171.126.5,111,udp,CON,0.004435,568,304,31,...,0,10,13,6,5,1,1,3,NaN,0
700000,59.166.0.0,6055,149.171.126.5,54145,tcp,FIN,0.072974,4238,60788,31,...,0,13,13,6,7,1,1,2,NaN,0

In [37]:
data_2 = pd.read_csv('/content/drive/MyDrive/Research Project/UNSW-NB15_2.csv', header=None)
data_2

<ipython-input-37-76a16e2d4c94>:1: DtypeWarning: Columns (3,39,47) have mixed types. Specify dtype option on import or set low_memory=False.
  data_2 = pd.read_csv('/content/drive/MyDrive/Research Project/UNSW-NB15_2.csv', header=None)

,0,1,2,3,4,5,6,7,8,9,...,39,40,41,42,43,44,45,46,47,48
0,59.166.0.0,6055,149.171.126.5,54145,tcp,FIN,0.072974,4238,60788,31,...,0,13,13,6,7,1,1,2,NaN,0
1,59.166.0.0,7832,149.171.126.3,5607,tcp,FIN,0.144951,5174,91072,31,...,0,13,13,6,7,1,1,2,NaN,0
2,59.166.0.8,11397,149.171.126.6,21,tcp,FIN,0.116107,2934,3742,31,...,1,1,2,7,5,1,1,4,NaN,0
3,59.166.0.0,3804,149.171.126.3,53,udp,CON,0.000986,146,178,31,...,0,13,13,6,7,1,1,2,NaN,0
4,59.166.0.8,14339,149.171.126.6,14724,tcp,FIN,0.038480,8928,320,31,...,0,8,20,7,5,1,1,4,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
699996,149.171.126.18,1043,175.45.176.3,53,udp,INT,0.000005,264,0,60,...,,19,19,19,19,19,19,19,NaN,0
699997,149.171.126.18,1043,175.45.176.3,53,udp,INT,0.000005,264,0,60,...,,19,19,19,19,19,19,19,NaN,0
699998,149.171.126.18,1043,175.45.176.3,53,udp,INT,0.000005,264,0,60,...,,19,19,19,19,19,19,19,NaN,0
699999,149.171.126.18,1043,175.45.176.3,53,udp,INT,0.000005,264,0,60,...,,19,19,19,19,19,19,19,NaN,0
700000,59.166.0.1,18247,149.171.126.4,7662,tcp,FIN,0.119596,4550,68342,31,...,,6,2,2,5,1,1,2,NaN,0

In [38]:
data_3 = pd.read_csv('/content/drive/MyDrive/Research Project/UNSW-NB15_3.csv', header=None)
data_3

,0,1,2,3,4,5,6,7,8,9,...,39,40,41,42,43,44,45,46,47,48
0,59.166.0.1,18247,149.171.126.4,7662,tcp,FIN,0.119596,4550,68342,31,...,,6,2,2,5,1,1,2,NaN,0
1,59.166.0.3,54771,149.171.126.2,27709,tcp,FIN,0.650574,8928,320,31,...,,3,5,2,4,1,1,4,NaN,0
2,59.166.0.8,13289,149.171.126.9,5190,tcp,FIN,0.007980,2158,2464,31,...,,3,5,1,1,1,1,3,NaN,0
3,149.171.126.18,1043,175.45.176.3,53,udp,INT,0.000005,264,0,60,...,,19,19,19,19,19,19,19,NaN,0
4,149.171.126.18,1043,175.45.176.3,53,udp,INT,0.000005,264,0,60,...,,19,19,19,19,19,19,19,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
699996,59.166.0.0,2111,149.171.126.5,53,udp,CON,0.001035,146,178,31,...,,1,3,4,3,1,1,4,NaN,0
699997,59.166.0.5,49044,149.171.126.3,30639,tcp,FIN,0.220630,424,8824,31,...,,3,3,3,3,1,1,4,NaN,0
699998,59.166.0.6,37717,149.171.126.7,35667,tcp,FIN,0.031576,2646,25564,31,...,,7,6,7,4,1,1,3,NaN,0
699999,59.166.0.2,1768,149.171.126.7,64122,tcp,FIN,0.096835,4862,82782,31,...,,6,6,7,7,1,1,2,NaN,0
700000,59.166.0.9,7045,149.171.126.7,25,tcp,FIN,0.201886,37552,3380,31,...,,2,2,7,4,1,1,3,NaN,0

In [39]:
data_4 = pd.read_csv('/content/drive/MyDrive/Research Project/UNSW-NB15_4.csv', header=None)
data_4

,0,1,2,3,4,5,6,7,8,9,...,39,40,41,42,43,44,45,46,47,48
0,59.166.0.9,7045,149.171.126.7,25,tcp,FIN,0.201886,37552,3380,31,...,,2,2,7,4,1,1,3,NaN,0
1,59.166.0.9,9685,149.171.126.2,80,tcp,FIN,5.864748,19410,1087890,31,...,,3,1,4,4,1,1,1,NaN,0
2,59.166.0.2,1421,149.171.126.4,53,udp,CON,0.001391,146,178,31,...,,3,5,2,7,1,1,4,NaN,0
3,59.166.0.2,21553,149.171.126.2,25,tcp,FIN,0.053948,37812,3380,31,...,,1,1,4,7,1,1,3,NaN,0
4,59.166.0.8,45212,149.171.126.4,53,udp,CON,0.000953,146,178,31,...,,2,5,2,1,1,1,2,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
440039,59.166.0.5,33094,149.171.126.7,43433,tcp,FIN,0.087306,320,1828,31,...,,1,2,3,3,1,1,3,NaN,0
440040,59.166.0.7,20848,149.171.126.4,21,tcp,CON,0.365058,456,346,31,...,2,2,2,2,2,2,2,2,NaN,0
440041,59.166.0.3,21511,149.171.126.9,21,tcp,CON,6.335154,1802,2088,31,...,2,2,2,4,2,2,2,2,NaN,0
440042,59.166.0.9,35433,149.171.126.0,80,tcp,CON,2.200934,3498,166054,31,...,,1,1,2,4,2,2,2,NaN,0
440043,175.45.176.0,17293,149.171.126.17,110,tcp,CON,0.942984,574,676,62,...,,1,1,2,4,2,2,2,Exploits,1

In [40]:
data_1.head()

,0,1,2,3,4,5,6,7,8,9,...,39,40,41,42,43,44,45,46,47,48
0,59.166.0.0,1390,149.171.126.6,53,udp,CON,0.001055,132,164,31,...,0,3,7,1,3,1,1,1,NaN,0
1,59.166.0.0,33661,149.171.126.9,1024,udp,CON,0.036133,528,304,31,...,0,2,4,2,3,1,1,2,NaN,0
2,59.166.0.6,1464,149.171.126.7,53,udp,CON,0.001119,146,178,31,...,0,12,8,1,2,2,1,1,NaN,0
3,59.166.0.5,3593,149.171.126.5,53,udp,CON,0.001209,132,164,31,...,0,6,9,1,1,1,1,1,NaN,0
4,59.166.0.3,49664,149.171.126.0,53,udp,CON,0.001169,146,178,31,...,0,7,9,1,1,1,1,1,NaN,0

In [41]:
data_2.head()

,0,1,2,3,4,5,6,7,8,9,...,39,40,41,42,43,44,45,46,47,48
0,59.166.0.0,6055,149.171.126.5,54145,tcp,FIN,0.072974,4238,60788,31,...,0,13,13,6,7,1,1,2,NaN,0
1,59.166.0.0,7832,149.171.126.3,5607,tcp,FIN,0.144951,5174,91072,31,...,0,13,13,6,7,1,1,2,NaN,0
2,59.166.0.8,11397,149.171.126.6,21,tcp,FIN,0.116107,2934,3742,31,...,1,1,2,7,5,1,1,4,NaN,0
3,59.166.0.0,3804,149.171.126.3,53,udp,CON,0.000986,146,178,31,...,0,13,13,6,7,1,1,2,NaN,0
4,59.166.0.8,14339,149.171.126.6,14724,tcp,FIN,0.038480,8928,320,31,...,0,8,20,7,5,1,1,4,NaN,0

In [42]:
data_3.head()

,0,1,2,3,4,5,6,7,8,9,...,39,40,41,42,43,44,45,46,47,48
0,59.166.0.1,18247,149.171.126.4,7662,tcp,FIN,0.119596,4550,68342,31,...,,6,2,2,5,1,1,2,NaN,0
1,59.166.0.3,54771,149.171.126.2,27709,tcp,FIN,0.650574,8928,320,31,...,,3,5,2,4,1,1,4,NaN,0
2,59.166.0.8,13289,149.171.126.9,5190,tcp,FIN,0.007980,2158,2464,31,...,,3,5,1,1,1,1,3,NaN,0
3,149.171.126.18,1043,175.45.176.3,53,udp,INT,0.000005,264,0,60,...,,19,19,19,19,19,19,19,NaN,0
4,149.171.126.18,1043,175.45.176.3,53,udp,INT,0.000005,264,0,60,...,,19,19,19,19,19,19,19,NaN,0

In [43]:
data_4.head()

,0,1,2,3,4,5,6,7,8,9,...,39,40,41,42,43,44,45,46,47,48
0,59.166.0.9,7045,149.171.126.7,25,tcp,FIN,0.201886,37552,3380,31,...,,2,2,7,4,1,1,3,NaN,0
1,59.166.0.9,9685,149.171.126.2,80,tcp,FIN,5.864748,19410,1087890,31,...,,3,1,4,4,1,1,1,NaN,0
2,59.166.0.2,1421,149.171.126.4,53,udp,CON,0.001391,146,178,31,...,,3,5,2,7,1,1,4,NaN,0
3,59.166.0.2,21553,149.171.126.2,25,tcp,FIN,0.053948,37812,3380,31,...,,1,1,4,7,1,1,3,NaN,0
4,59.166.0.8,45212,149.171.126.4,53,udp,CON,0.000953,146,178,31,...,,2,5,2,1,1,1,2,NaN,0

In [44]:
features_df = pd.read_csv('/content/drive/MyDrive/Research Project/UNSW-NB15_features.csv', encoding="latin1")
headers = list(features_df["Name"])

In [45]:
# !pip install chardet

In [46]:
# import chardet

# with open('/content/drive/MyDrive/Research Project/UNSW-NB15_features.csv', 'rb') as f:
#     encoding = chardet.detect(f.read())['encoding']

In [47]:
# features_df = pd.read_csv('/content/drive/MyDrive/Research Project/UNSW-NB15_features.csv', encoding=encoding)
# features_df

In [48]:
# Appending all four DataFrames into one
final_df = pd.concat([data_1, data_2, data_3, data_4], ignore_index=True, axis=0)

# Display the final DataFrame
print(final_df)

                   0      1               2      3    4    5         6     7   \
0          59.166.0.0   1390   149.171.126.6     53  udp  CON  0.001055   132
1          59.166.0.0  33661   149.171.126.9   1024  udp  CON  0.036133   528
2          59.166.0.6   1464   149.171.126.7     53  udp  CON  0.001119   146
3          59.166.0.5   3593   149.171.126.5     53  udp  CON  0.001209   132
4          59.166.0.3  49664   149.171.126.0     53  udp  CON  0.001169   146
...               ...    ...             ...    ...  ...  ...       ...   ...
2540042    59.166.0.5  33094   149.171.126.7  43433  tcp  FIN  0.087306   320
2540043    59.166.0.7  20848   149.171.126.4     21  tcp  CON  0.365058   456
2540044    59.166.0.3  21511   149.171.126.9     21  tcp  CON  6.335154  1802
2540045    59.166.0.9  35433   149.171.126.0     80  tcp  CON  2.200934  3498
2540046  175.45.176.0  17293  149.171.126.17    110  tcp  CON  0.942984   574

             8   9   ...  39  40  41 42  43  44  45  46        47  48
0           164  31  ...   0   3   7  1   3   1   1   1       NaN   0
1           304  31  ...   0   2   4  2   3   1   1   2       NaN   0
2           178  31  ...   0  12   8  1   2   2   1   1       NaN   0
3           164  31  ...   0   6   9  1   1   1   1   1       NaN   0
4           178  31  ...   0   7   9  1   1   1   1   1       NaN   0
...         ...  ..  ...  ..  ..  .. ..  ..  ..  ..  ..       ...  ..
2540042    1828  31  ...       1   2  3   3   1   1   3       NaN   0
2540043     346  31  ...   2   2   2  2   2   2   2   2       NaN   0
2540044    2088  31  ...   2   2   2  4   2   2   2   2       NaN   0
2540045  166054  31  ...       1   1  2   4   2   2   2       NaN   0
2540046     676  62  ...       1   1  2   4   2   2   2  Exploits   1

[2540047 rows x 49 columns]

In [49]:
final_df.columns=headers

In [50]:
final_df.head()

,srcip,sport,dstip,dsport,proto,state,dur,sbytes,dbytes,sttl,...,ct_ftp_cmd,ct_srv_src,ct_srv_dst,ct_dst_ltm,ct_src_ ltm,ct_src_dport_ltm,ct_dst_sport_ltm,ct_dst_src_ltm,attack_cat,Label
0,59.166.0.0,1390,149.171.126.6,53,udp,CON,0.001055,132,164,31,...,0,3,7,1,3,1,1,1,NaN,0
1,59.166.0.0,33661,149.171.126.9,1024,udp,CON,0.036133,528,304,31,...,0,2,4,2,3,1,1,2,NaN,0
2,59.166.0.6,1464,149.171.126.7,53,udp,CON,0.001119,146,178,31,...,0,12,8,1,2,2,1,1,NaN,0
3,59.166.0.5,3593,149.171.126.5,53,udp,CON,0.001209,132,164,31,...,0,6,9,1,1,1,1,1,NaN,0
4,59.166.0.3,49664,149.171.126.0,53,udp,CON,0.001169,146,178,31,...,0,7,9,1,1,1,1,1,NaN,0

In [51]:
len(final_df)

2540047

In [52]:
events_df = pd.read_csv('/content/drive/MyDrive/Research Project/UNSW-NB15_LIST_EVENTS.csv', encoding="latin1")

In [53]:
events_df.head()

  Attack category Attack subcategory  Number of events
0          normal                NaN           2218761
1        Fuzzers                 FTP               558
2        Fuzzers                HTTP              1497
3        Fuzzers                 RIP              3550
4        Fuzzers                 SMB              5245

In [54]:
# Print all column names
print(final_df.columns)

Index(['srcip', 'sport', 'dstip', 'dsport', 'proto', 'state', 'dur', 'sbytes',
       'dbytes', 'sttl', 'dttl', 'sloss', 'dloss', 'service', 'Sload', 'Dload',
       'Spkts', 'Dpkts', 'swin', 'dwin', 'stcpb', 'dtcpb', 'smeansz',
       'dmeansz', 'trans_depth', 'res_bdy_len', 'Sjit', 'Djit', 'Stime',
       'Ltime', 'Sintpkt', 'Dintpkt', 'tcprtt', 'synack', 'ackdat',
       'is_sm_ips_ports', 'ct_state_ttl', 'ct_flw_http_mthd', 'is_ftp_login',
       'ct_ftp_cmd', 'ct_srv_src', 'ct_srv_dst', 'ct_dst_ltm', 'ct_src_ ltm',
       'ct_src_dport_ltm', 'ct_dst_sport_ltm', 'ct_dst_src_ltm', 'attack_cat',
       'Label'],
      dtype='object')

In [55]:
# Printing each column name and its data type
print(final_df.dtypes)

srcip                object
sport                object
dstip                object
dsport               object
proto                object
state                object
dur                 float64
sbytes                int64
dbytes                int64
sttl                  int64
dttl                  int64
sloss                 int64
dloss                 int64
service              object
Sload               float64
Dload               float64
Spkts                 int64
Dpkts                 int64
swin                  int64
dwin                  int64
stcpb                 int64
dtcpb                 int64
smeansz               int64
dmeansz               int64
trans_depth           int64
res_bdy_len           int64
Sjit                float64
Djit                float64
Stime                 int64
Ltime                 int64
Sintpkt             float64
Dintpkt             float64
tcprtt              float64
synack              float64
ackdat              float64
is_sm_ips_ports       int64
ct_state_ttl          int64
ct_flw_http_mthd    float64
is_ftp_login        float64
ct_ftp_cmd           object
ct_srv_src            int64
ct_srv_dst            int64
ct_dst_ltm            int64
ct_src_ ltm           int64
ct_src_dport_ltm      int64
ct_dst_sport_ltm      int64
ct_dst_src_ltm        int64
attack_cat           object
Label                 int64
dtype: object

In [56]:
# Print the first ten values of 'ColumnName'
print(final_df['srcip'].head(10))

0     59.166.0.0
1     59.166.0.0
2     59.166.0.6
3     59.166.0.5
4     59.166.0.3
5     59.166.0.0
6     59.166.0.6
7    10.40.182.3
8     59.166.0.5
9     59.166.0.7
Name: srcip, dtype: object

In [57]:
# prompt: can you print the different values of the attack_cat and label column?

print(final_df['attack_cat'].value_counts())
print(final_df['Label'].value_counts())

Generic             215481
Exploits             44525
 Fuzzers             19195
DoS                  16353
 Reconnaissance      12228
 Fuzzers              5051
Analysis              2677
Backdoor              1795
Reconnaissance        1759
 Shellcode            1288
Backdoors              534
Shellcode              223
Worms                  174
Name: attack_cat, dtype: int64
0    2218764
1     321283
Name: Label, dtype: int64

In [58]:
# prompt: can you give me the code to store all the records without DOS as their attack_Cat in a seperaete dataframe?

data_df = final_df[final_df['attack_cat'] != 'DoS']
data_df.head()

,srcip,sport,dstip,dsport,proto,state,dur,sbytes,dbytes,sttl,...,ct_ftp_cmd,ct_srv_src,ct_srv_dst,ct_dst_ltm,ct_src_ ltm,ct_src_dport_ltm,ct_dst_sport_ltm,ct_dst_src_ltm,attack_cat,Label
0,59.166.0.0,1390,149.171.126.6,53,udp,CON,0.001055,132,164,31,...,0,3,7,1,3,1,1,1,NaN,0
1,59.166.0.0,33661,149.171.126.9,1024,udp,CON,0.036133,528,304,31,...,0,2,4,2,3,1,1,2,NaN,0
2,59.166.0.6,1464,149.171.126.7,53,udp,CON,0.001119,146,178,31,...,0,12,8,1,2,2,1,1,NaN,0
3,59.166.0.5,3593,149.171.126.5,53,udp,CON,0.001209,132,164,31,...,0,6,9,1,1,1,1,1,NaN,0
4,59.166.0.3,49664,149.171.126.0,53,udp,CON,0.001169,146,178,31,...,0,7,9,1,1,1,1,1,NaN,0

In [59]:
# Checking data_df to see if all DOS attack_Cat have been removed
print(data_df['attack_cat'].value_counts())
print(data_df['Label'].value_counts())

Generic             215481
Exploits             44525
 Fuzzers             19195
 Reconnaissance      12228
 Fuzzers              5051
Analysis              2677
Backdoor              1795
Reconnaissance        1759
 Shellcode            1288
Backdoors              534
Shellcode              223
Worms                  174
Name: attack_cat, dtype: int64
0    2218764
1     304930
Name: Label, dtype: int64

In [60]:
# prompt: find all null values in attack_cat column?

null_values = data_df['attack_cat'].isnull().sum()
print(f"Number of null values in attack_cat column: {null_values}")

Number of null values in attack_cat column: 2218764

In [61]:
# prompt: create a new column and map ever recordy with a NaN value as 0 and anything else as 1 call the column 'label'

data_df['label'] = data_df['attack_cat'].apply(lambda x: 1 if pd.notnull(x) else 0)

<ipython-input-61-1bbca4ecc91a>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_df['label'] = data_df['attack_cat'].apply(lambda x: 1 if pd.notnull(x) else 0)

In [62]:
# prompt: print the number of different values in the label column

print(data_df['label'].value_counts())

0    2218764
1     304930
Name: label, dtype: int64

In [63]:
# prompt: delete the Label column

del data_df['Label']

In [64]:
# prompt: can you delete the attack_cat column and rename the label column as attack_cat

data_df.drop(columns=['attack_cat'], inplace=True)
data_df.rename(columns={'label': 'attack_cat'}, inplace=True)

<ipython-input-64-5473a91e78e5>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_df.drop(columns=['attack_cat'], inplace=True)
<ipython-input-64-5473a91e78e5>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_df.rename(columns={'label': 'attack_cat'}, inplace=True)

In [65]:
# prompt: can you show me count of diffrent values in the attack_cat column

print(data_df['attack_cat'].value_counts())

0    2218764
1     304930
Name: attack_cat, dtype: int64

In [66]:
# pip install scikit-learn
# from sklearn.model_selection import train_test_split


# # Splitting the dataset into training and testing sets
# train_df, test_df = train_test_split(final_df, test_size=0.3, random_state=42)

# # train_df will contain 70% of the data, test_df will contain 30%
# print("Training set:")
# print(train_df)
# print("\nTesting set:")
# print(test_df)

In [67]:
# prompt: can you write code to store the dataframe into a csv file in a particular folder on google drive?

data_df.to_csv('/content/drive/MyDrive/Research Project/Final_dataset.csv')